apiVersion: apps/v1
kind: Deployment
metadata:
  name: smb-file-manager-prod-deployment
  namespace: smb-file-manager-prod
  labels:
    app: smb-file-manager-prod
spec:
  selector:
    matchLabels:
      app: smb-file-manager-prod
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: smb-file-manager-prod
    spec:
      containers:
      - name: smb-file-manager-prod
        image: vincentbuiwork/smb-file-manager:prod
        imagePullPolicy: Always
        resources:
          requests:
            memory: 500M
          limits:
            memory: 2Gi
        livenessProbe:
          tcpSocket:
            port: 81
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 81
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 81
      restartPolicy: Always
