apiVersion: v1
kind: Service
metadata:
  name: smb-file-manager-stage-service
  labels:
    app: smb-file-manager-stage
spec:
  type: LoadBalancer
  loadBalancerIP: 10.24.24.113
  externalIPs:
  - 10.24.24.113
  ports:
  - name: http
    port: 82 #local out port
    protocol: TCP
    targetPort: 82 # container port
  selector:
    app: smb-file-manager-stage #find all pod with app name
  sessionAffinity: None
